<?php
require __DIR__ . '/bootstrap.php';
$passed=0;
function check($ok, $name) { global $passed; if (!$ok) { throw new RuntimeException('FAIL: '.$name); } $passed++; }
function throws($callback, $code) { try {$callback();} catch (RuntimeException $e) { check($e->getMessage()===$code, $code); return; } throw new RuntimeException('Expected: '.$code); }
[$row,$x]=setup(); $p=Oldies_X_News_Policy::class;
check($p::evidence($row,$x), 'Low-risk evidence passes after actual review');
$death=$row; $death['headline']='Elton John hospitalized after surgery';
check(!$p::evidence($death,$x),'Single source health is held');
$pair=$x; $pair['evidence']['second']='https://www.eltonjohn.com/news/statement';
check($p::evidence($death,$pair),'Reliable plus official statement passes');
$pair['evidence']['primary']='https://www.smoothradio.com/news/artist'; $pair['evidence']['second']='https://www.goldradio.com/news/artist';
check(!$p::evidence($death,$pair),'Same publisher is not independent');
$pair['evidence']['primary']='https://www.bbc.com/news/one'; $pair['evidence']['second']='https://www.theguardian.com/music/two';
check($p::evidence($death,$pair),'Independent publishers pass');
$pair['evidence']['reviewed_by']=null; check(!$p::evidence($death,$pair),'Two URLs alone never verify');
$pair['evidence']['reviewed_by']=42; $pair['evidence']['note']=''; check(!$p::evidence($death,$pair),'Evidence note mandatory');
$pair['evidence']['note']='reviewed'; $pair['evidence']['second']='https://unknown.test/claim'; check(!$p::evidence($death,$pair),'Unknown evidence host held');
foreach(['died','hospitalised','cancer','lawsuit','allegations','arrested','health','vefat','kalp ameliyatı','dava'] as $keyword) { check($p::sensitive(['headline'=>'Artist '.$keyword],[]),'Sensitive '.$keyword); }
check($p::weight('Çığ Şölen İstanbul')===18, 'Turkish Unicode weighted correctly');
check($p::weight('🎸')===2,'Simple emoji weighted');
check($p::weight('https://oldiesradyo.com/en/'.str_repeat('a',500))===23,'Long URL weighted 23');
check($p::textError($x['text'],$x['wp_url'])==='','Valid edited English text');
check($p::textError(str_repeat('a',300).' '.$x['wp_url'],$x['wp_url'])==='CHARACTER_LIMIT','Oversize rejected');
check($p::textError('Read https://evil.test/story',$x['wp_url'])==='ONE_OLDIES_LINK_REQUIRED','Third party URL rejected');
check($p::textError($x['text'].' https://example.com',$x['wp_url'])==='ONE_OLDIES_LINK_REQUIRED','Two URLs rejected');
check($p::textError($x['text'].' #one #two #three #four',$x['wp_url'])==='HASHTAG_LIMIT','Hashtag spam rejected');
check($p::weight("\xff")===PHP_INT_MAX,'Invalid Unicode rejected');
check($p::weight("Text\x00")===PHP_INT_MAX,'Invisible control rejected');
check($p::canonical('https://www.oldiesradyo.com/en/news/?utm_source=x&fbclid=abc')===$p::canonical('https://oldiesradyo.com/en/news/'),'Tracking dedupe');
check($p::canonical('https://oldiesradyo.com@evil.test/news')==='','Userinfo URL rejected');
check($p::canonical('https://oldiesradyo.com:444/news')==='','Nonstandard port rejected');
check($p::canonical('javascript:alert(1)')==='','Unsupported scheme rejected');
$other=$x;$other['wp_url'].='?utm_source=two'; check($p::similar($x,$other),'Same news URL duplicate');
$other=$x;$other['wp_url']='https://oldiesradyo.com/en/another';check($p::similar($x,$other),'Same event key duplicate');
$other['story_key']='different';$other['artist']='Cher';check(!$p::similar($x,$other),'Different artist distinct');
$other=$x;$other['wp_url']='https://oldiesradyo.com/en/another';$other['story_key']='two';$other['text']='Elton John opens vaults with restored archival release today';check($p::similar($x,$other),'Artist-constrained paraphrase duplicate');
check($p::initialStatus($death,$x)==='HOLD','Health stays held');
$new=$x;$new['wp_url']='';check($p::initialStatus($row,$new)==='NEWS CANDIDATE','No WordPress article candidate only');
$new=$x;$new['approved_by']=null;check($p::initialStatus($row,$new)==='VERIFIED','No automatic approval');
$new['status']='POSTED';check($p::initialStatus($row,$new)==='POSTED','Posted status stable');
check($p::draft('',$x['wp_url'])==='','No fabricated draft without English excerpt');
check($p::weight($p::draft(str_repeat('A good announcement. ',40),$x['wp_url']))<=280,'Draft fits limit');
$store=new Oldies_X_News_Store();check($store->available(),'Existing table contract accepted');
$store->save($row,$x);$saved=json_decode($GLOBALS['wpdb']->data[1]['metadata'],true);check($saved['existing']['keep']==='do not overwrite','Other metadata preserved');
check($GLOBALS['wpdb']->data[1]['status']==='PUBLISHED'&&$GLOBALS['wpdb']->data[1]['en_content']==='original English article','Main news state and body untouched');
throws(fn()=>$store->save($row,$x),'STATE_CHANGED');
throws(fn()=>Oldies_X_News_Store::metadata(['metadata'=>'bad JSON']),'INVALID_EXISTING_METADATA');
$GLOBALS['wpdb']->columns=[];check(!$store->available(),'Unknown schema blocked');$GLOBALS['wpdb']->columns=['id','metadata','en_post_id','headline','updated_at','fingerprint','artist_topic','article_url'];
$GLOBALS['wpdb']->lockAvailable=false;throws(fn()=>$store->locked(fn()=>true),'X_BUSY');$GLOBALS['wpdb']->lockAvailable=true;
try{$store->locked(fn()=>throw new RuntimeException('test'));}catch(RuntimeException $e){}check($GLOBALS['wpdb']->releases===1,'Lock released on exception');
$GLOBALS['wpdb']->data=[];
for($i=2;$i<=205;$i++){ $d=$x;$d['wp_url']='https://oldiesradyo.com/en/'.$i;$d['story_key']='key'.$i;$d['artist']='Other';$d['status']='POSTED';$GLOBALS['wpdb']->data[$i]=['id'=>$i,'metadata'=>json_encode(['x_news'=>$d])]; }
$d=$x;$d['status']='OUTCOME_UNKNOWN';$GLOBALS['wpdb']->data[999]=['id'=>999,'metadata'=>json_encode(['x_news'=>$d])];
check($store->duplicate(1,$x),'Old/uncertain duplicate found beyond 200 rows');
$d=$x;$d['status']='FAILED';$GLOBALS['wpdb']->data=[9=>['id'=>9,'metadata'=>json_encode(['x_news'=>$d])]];check(!$store->duplicate(1,$x),'Definitive rejection is not posted');
check(Oldies_X_News_Publisher::budgetError(0,0.2)==='API_DISABLED_ZERO_COST_MODE','Default blocks paid requests');
putenv('OLDIES_X_API_ENABLED=true');check(Oldies_X_News_Publisher::budgetError(0,0.2)==='PAID_API_NOT_AUTHORIZED','Missing budget blocks requests');
putenv('OLDIES_X_MAX_REQUEST_USD=0.2');putenv('OLDIES_X_MONTHLY_BUDGET_USD=18');check(Oldies_X_News_Publisher::budgetError(17.9,0.2)==='PAID_API_NOT_AUTHORIZED','Monthly cap blocks overspend');
check(Oldies_X_News_Publisher::budgetError(0,0.2)==='','Positive explicit budget accepted');
putenv('OLDIES_X_USER_ACCESS_TOKEN=fake-unit-test-token');putenv('OLDIES_X_OAUTH2_SCOPES=tweet.read users.read');throws(fn()=>Oldies_X_News_Publisher::authorization('POST','https://api.x.com/2/tweets'),'USER_WRITE_SCOPES_REQUIRED');
putenv('OLDIES_X_OAUTH2_SCOPES=tweet.read tweet.write users.read');
$calls=0;$pub=new Oldies_X_News_Publisher(function($url,$args)use(&$calls,$x){$calls++;check($url==='https://api.x.com/2/tweets'&&json_decode($args['body'],true)===['text'=>$x['text']],'API text/link-only payload');return ['response'=>['code'=>201],'body'=>'{"data":{"id":"123456789"}}'];});
check($pub->send($x['text'])['status']==='POSTED'&&$calls===1,'Successful post only once');
$pub=new Oldies_X_News_Publisher(fn()=>new WP_Error('timeout'));check($pub->send($x['text'])['status']==='OUTCOME_UNKNOWN','Timeout never blind-retries');
$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>503],'body'=>'']);check($pub->send($x['text'])['status']==='OUTCOME_UNKNOWN','5xx uncertain');
$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>201],'body'=>'{}']);check($pub->send($x['text'])['status']==='OUTCOME_UNKNOWN','Malformed 201 uncertain');
$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>429],'body'=>'','headers'=>['x-rate-limit-reset'=>time()+300]]);$result=$pub->send($x['text']);check($result['status']==='FAILED'&&$result['retry_after']>time()+200,'429 safe backoff');
$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>401],'body'=>'secret that must not escape']);$result=$pub->send($x['text']);check(!str_contains(json_encode($result),'secret')&&$result['status']==='FAILED','API error body never exposed');
putenv('OLDIES_X_EXPECTED_USERNAME=OldiesTest');$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>200],'body'=>'{"data":{"id":"42","username":"WrongAccount"}}']);throws(fn()=>$pub->identityCheck(0),'X_ACCOUNT_MISMATCH');
$pub=new Oldies_X_News_Publisher(fn()=>['response'=>['code'=>200],'body'=>'{"data":{"id":"42","username":"OldiesTest"}}']);$identity=$pub->identityCheck(0);check(Oldies_X_News_Publisher::identityValid($identity),'Identity matches authorized user');
$identity['checked_at']=gmdate('c',time()-90000);check(!Oldies_X_News_Publisher::identityValid($identity),'Expired identity rejected');
[$row,$x]=setup();$h=Oldies_X_News_Controller::approvalHash($row,$x);$row['summary_raw']='Changed source story';check($h!==Oldies_X_News_Controller::approvalHash($row,$x),'Changed source invalidates approval');
[$row,$x]=setup();$GLOBALS['languages'][10]='tr';check(Oldies_X_News_Controller::article($row)['wp_url']==='','Turkish post not shared as English');
$GLOBALS['languages'][10]='en';$GLOBALS['posts'][10]->post_status='draft';check(Oldies_X_News_Controller::article($row)['wp_url']==='','Unpublished English post blocked');
$GLOBALS['posts'][10]->post_status='publish';$GLOBALS['posts'][10]->post_type='page';check(Oldies_X_News_Controller::article($row)['wp_url']==='','Legacy project page not imported');
[$row,$x]=setup();$GLOBALS['urls'][10]='https://elsewhere.test/news';check(Oldies_X_News_Controller::article($row)['wp_url']==='','Offsite WordPress permalink blocked');
[$row,$x]=setup();Oldies_X_News_Controller::published('publish','draft',$GLOBALS['posts'][10]);$saved=json_decode($GLOBALS['wpdb']->data[1]['metadata'],true);check(isset($saved['x_news'])&&$saved['existing']['keep']==='do not overwrite','Publish hook prepares only known queue row');
check($GLOBALS['network_calls']===0,'Publish hook never calls X');
echo json_encode(['passed'=>$passed,'failed'=>0,'network'=>'mock only'],JSON_PRETTY_PRINT)."\n";
